[gdrive]
type = drive
scope = drive
service_account_file = /secrets/sacred-flash-452501-m0-4cabaf4ceddc.json
team_drive = 0ANrWRo_JRi5mUk9PVA

[gcs]
type = google cloud storage
service_account_file = /secrets/sacred-flash-452501-m0-4cabaf4ceddc.json
location = US
